### ISSUE TITLE
Multiple escaped slashes not correctly unescaped

### ISSUE THREAD

**Issue by goofballLogic** [flitbit/json-ptr#1]
e.g. in the following snippet, the path is decoded incorrectly:

    node
    > var pointer = "/a/http:~1~1www.test.com~1b/c";
    > require( "json-ptr" ).decodePointer( pointer );

Actual:

    [ 'a', 'http:/~1www.test.com~1b', 'c' ]

Expected:

    [ 'a', 'http://www.test.com/b', 'c' ]

Note that this is critical use case when processing json-ld documents with JSON pointers

**Comment by flitbit** [comment]
Fixed in version 0.3+
