### ISSUE TITLE
Creation of non-existent elements in array doesn't work

### ISSUE THREAD

**Issue by chrisknight32** [flitbit/json-ptr#11]
This is related to what #10 addresses. That issue fixes when arrays don't exist to begin with but there is also the problem that when you set a value using force = true, and the path leads through an array element that doesn't exist yet, you get the final value inserted into the array rather than objects being created as expected.

```javascript
ptr = require('json-ptr')

a = {
    Foo: []
}

p = ptr.create('/Foo/0/Bar/Baz');

// Succeeds but with incorrect results.
p.set(a, 5, true);
// a is now { Foo: [5] }
// a should be
// {
//   Foo: [
//     {
//       Bar: {
//         Baz: 5
//       }
//     }
//   ]
// }
console.log(a);

p = ptr.create('/Foo/Bar/Baz');

b = {
    Foo: {}
}

p.set(b, 5, true);
// Works as you'd expect.
// b is now
// {
//   Foo: {
//     Bar: {
//       Baz: 5
//     }
//   }
// }
console.log(b);
```

**Comment by flitbit** [comment]
Fixed in release 1.1.0. See [issue-11.js](https://github.com/flitbit/json-ptr/blob/master/examples/issues/issue-11.js) and the [test](https://github.com/flitbit/json-ptr/blob/53832f9b2a5d7c7a04b68e099e0335a93b454539/test/tests.js#L995-L1006)
