### ISSUE TITLE
missing tslib dependency since 1.3.0

### ISSUE THREAD

**Issue by mfukala** [flitbit/json-ptr#23]
since version 1.3.0 node_modules/json-ptr/dist/index.js does require tslib but package.json does not declare this dependency. Any package depending on json-ptr that does not directly or indirectly bring tslib itself fail because of this problem.
I've noticed your package-lock.json contains tslib so it's possibly why you didn't notice this issue.

**Comment by flitbit** [comment]
Please verify whether `json-ptr@1.3.2-master.b0d7d5e` and I'll get it published as `v1.3.2`.

**Comment by mfukala** [comment]
> Please verify whether `json-ptr@1.3.2-master.b0d7d5e` resolves the issue and I'll get it published as `v1.3.2`.

Yes, json-ptr@1.3.2-master.b0d7d5e fixes this problem, please publish. Thank you for the fix.

**Comment by flitbit** [comment]
Fixed with v1.3.2
