### ISSUE TITLE
Many functions are missing in 1.3.1, despite this not being a major version

### ISSUE THREAD

**Issue by jwalton** [flitbit/json-ptr#24]
My library relies on json-ptr 1.1.1, but now that 1.3.1 is out, it's unfortunately [broken my library](https://github.com/exegesis-js/exegesis/issues/146).  It seems a number of exported function have been removed, even though this is not a semver major release (`create`, `has`, `decode` to name a few).  Could we add these back in and/or republish the last version that had these as 1.3.2, and then republish 1.3.1 as 2.0.0?

**Comment by Alan-Cha** [comment]
Hi! Thank you very much for this library! Unfortunately, I experienced similar problems and it has broken my library ([example 1](https://github.com/IBM/openapi-to-graphql/issues/339) and [example 2](https://github.com/IBM/openapi-to-graphql/pull/338)). I'm not sure what's the best path moving forward but I do think this should have been a major version. Just wanted to give you some feedback. Hope this will be resolved soon!

**Comment by flitbit** [comment]
I spent some time getting the docs tree built but clearly neglected to note that the global functions are now static functions of JsonPointer class... so `JsonPointer.create`, `JsonPointer.get`, `JsonPointer.has`, etc. etc. They have identical signatures and work the same as the  once global functions.

I also reviewed the Semver site and you are correct, major black eye not rolling the major version... but that ship has sailed.

**Comment by flitbit** [comment]
When I get done with the relative pointers (soon) I'll roll the major version. I've since noticed that some of my examples don't work due to this API change; I'll fix those too. Major tunnel vision getting 100% test coverage and the docs generated. Thanks for the feedback.

**Comment by flitbit** [comment]
I [documented in master branch where these functions went](https://github.com/flitbit/json-ptr#user-content-where-did-the-global-functions-go), please let me know if you have problems importing/using them from their new location.

Sorry about the inconvenience.

**Comment by svedbg** [comment]
You can just unpublish v1.3.2 and v1.3.1 and just publish as v2.0.0. It's better than leaving the breaking change
