### ISSUE TITLE
Arbitrary Code Execution in JsonPointer.get

### ISSUE THREAD

**Issue by zpbrent** [flitbit/json-ptr#30]
Hey maintainers @cehoffman @mortonfox @treybrisbane @chrishalbert ,  I have opened a PR (https://github.com/418sec/json-ptr/pull/3) which will fix the potential arbitrary code execution vulnerability in json-ptr. Please take a review.

If you are fine with that fix, please comment @huntr-helper - LGTM at https://github.com/418sec/json-ptr/pull/3, or if you need any modifications, please also comment on that PR. Thanks.

Ref: https://github.com/418sec/json-ptr/pull/3

**Comment by cerebralkungfu** [comment]
Fixed with the original report #28.
