### ISSUE TITLE
Use of ES6 prevents minification with UglifyJS

### ISSUE THREAD

**Issue by cehoffman** [flitbit/json-ptr#4]
The variable statements like `let` and the use of template strings [here](https://github.com/flitbit/json-ptr/blob/master/index.js#L208) are unable to be minified as tracked in https://github.com/mishoo/UglifyJS2/issues/448.

It would be nice if json-ptr in the releases directory at least was transpiled to ES5 for wider browser compatibility too. I notice you have babel in the dependencies and creating releases, but it letting the `let`, string templates, and `class` definitions through.

**Comment by bdesham** [comment]
Are there any plans to make a release with this fix included?
