### ISSUE TITLE
Mark https://www.npmjs.com/advisories/1706 as fixed

### ISSUE THREAD

**Issue by samtstern** [flitbit/json-ptr#40]
This library, as you know, has an outstanding vulnerability notice:
https://www.npmjs.com/advisories/1706

However I believe you actually patched/fixed this in `2.1.0`, it's just that NPM does not seem to know. I don't know how these things work, but could you get NPM to mark this as resolved at the proper version?

**Comment by cerebralkungfu** [comment]
I'll see what I can do.

**Comment by cerebralkungfu** [comment]
Several advisories updated, including NPM and GitHub, I've also advised NIST since it will eventually show there as well.
