### ISSUE TITLE
Document supported Node.js versions

### ISSUE THREAD

**Issue by kevinoid** [flitbit/json-ptr#43]
It appears that `json-ptr@3.0.0` requires Node.js 14 or later due to use of [optional chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining).  Presumably this is intentional?  It would be nice if this were mentioned in the README or in the [`engines` field in `package.json`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines).

Thanks for considering,
Kevin

**Comment by donal-tobin-sap** [comment]
> Not exactly intentional, but I did update the packaging/publishing in many ways... maybe I should have known. I'm not going to require Node.js 14... that seems too restrictive so I'll change the cjs output to be compatible with more outdated versions of Node and publish an update.

Is this something that you still intend to do?

**Comment by devinea** [comment]
@cerebralkungfu - I created a PR to fix this, let me know if anything else is required.
