### ISSUE TITLE
Can't get basic example to work.

### ISSUE THREAD

**Issue by reggi** [flitbit/json-ptr#47]
For some reason this does not work:

```js
const target = {}
JsonPointer.set(target, '/third', 'tenth')
console.log(target) // still empty {}
```

**Comment by reggi** [comment]
It seems to need existing values?

**Comment by cerebralkungfu** [comment]
As #44 pointed out, my documentation is broken, so it's a pain to figure out...

This [link should help](https://flitbit.github.io/json-ptr/classes/jsonpointer.html#set-1)... there's one more argument, `force`, which indicates to build the missing path in the object graph.
