### ISSUE TITLE
Literal property value 'e' is interpreted as a number

### ISSUE THREAD

**Issue by kamsar** [flitbit/json-ptr#48]
It appears that 'e' in a pointer path is interpreted as a number, which seems wrong since JS does not generally treat 'e' as a constant number and exponential notation requires a preceding digit ('1e7'). Adding an extra non-numeric character to the path, i.e. '/hi/eX', makes it behave as expected.

```
const { JsonPointer } = require('json-ptr');

// run `node index.js` in the terminal to repro

const obj = {};

const ptr = JsonPointer.create('/hi/e');

ptr.set(obj, 'hello', true);

console.log(`result`, obj);

// expected:
// { hi: {e: 'hello'} }

// got:
// { hi: [] }
```

Run it here:
https://stackblitz.com/edit/node-a9wd7r?file=index.js

**Comment by kamsar** [comment]
This can also be reproduced with other single-character property names such as 'x' that are not numbers so it may just be a bug not related to number parsing at all.

**Comment by cerebralkungfu** [comment]
verified in [branch bug/issue-48](/flitbit/json-ptr/tree/bug/issue-48)

running [examples/issues/issue-48.js](https://github.com/flitbit/json-ptr/blob/bef66fd4da8890ec1672864aa3f4fa3f8b4913a0/examples/issues/issue-48.js) illustrates... thanks for the working code to reproduce!

I'll fix it there.

**Comment by cerebralkungfu** [comment]
Upcoming v3.1.0
